name: Deploy Flet App to Pages

on:
  push:
    branches: [ main, master ] # Funciona em qualquer nome de branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ESTA É A PARTE QUE FALTAVA: Instala o Flutter antes do Flet pedir
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Versão estável compatível
          channel: 'stable'

      - name: Install Dependencies
        run: |
          pip install flet
          # Se você tiver outras bibliotecas, o GitHub vai ler seu requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          - name: Build Web
          run: |
          yes | flet build web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
